# Generated by Django 5.2.14 on 2026-05-28 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('servers', '0003_baselinescan_current_step_baselinescan_error_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChatLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_chat_id', models.BigIntegerField(unique=True)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('chat_type', models.CharField(choices=[('private', 'Private'), ('group', 'Group'), ('supergroup', 'Supergroup'), ('channel', 'Channel')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('allowed_notifications', models.JSONField(blank=True, default=list)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telegram_chat_links', to='accounts.account')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telegram_chat_links', to='servers.server')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_chat_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['account__name', 'telegram_chat_id'],
            },
        ),
        migrations.CreateModel(
            name='TelegramLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('chat_scope', models.CharField(choices=[('private', 'Private'), ('group', 'Group')], max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telegram_link_tokens', to='accounts.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_telegram_link_tokens', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telegram_link_tokens', to='servers.server')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('baseline_completed', 'Baseline completed'), ('finding_created', 'Finding created'), ('agent_offline', 'Agent offline'), ('agent_recovered', 'Agent recovered'), ('bootstrap_completed', 'Bootstrap completed'), ('bootstrap_failed', 'Bootstrap failed')], max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed')], default='pending', max_length=20)),
                ('dedupe_key', models.CharField(blank=True, max_length=255)),
                ('payload_redacted', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telegram_notifications', to='accounts.account')),
                ('chat_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='telegram_integration.telegramchatlink')),
                ('finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_notifications', to='servers.finding')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telegram_notifications', to='servers.server')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='telegramchatlink',
            index=models.Index(fields=['account', 'status'], name='telegram_in_account_dfc384_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramchatlink',
            index=models.Index(fields=['telegram_chat_id', 'status'], name='telegram_in_telegra_dac114_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramlinktoken',
            index=models.Index(fields=['account', 'created_at'], name='telegram_in_account_8b5bca_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramlinktoken',
            index=models.Index(fields=['token_hash'], name='telegram_in_token_h_17c74d_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramnotification',
            index=models.Index(fields=['account', 'notification_type', 'created_at'], name='telegram_in_account_502c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramnotification',
            index=models.Index(fields=['chat_link', 'dedupe_key', 'created_at'], name='telegram_in_chat_li_21bd83_idx'),
        ),
    ]
