# Generated by Django 5.2.14 on 2026-05-28 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0002_application_metadata_and_more'),
        ('diagnostics', '0002_diagnosticsession_source_and_more'),
        ('servers', '0003_baselinescan_current_step_baselinescan_error_message_and_more'),
        ('telegram_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramDiagnosticState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('selecting_server', 'Selecting server'), ('selecting_application', 'Selecting application'), ('selecting_problem_type', 'Selecting problem type'), ('awaiting_description', 'Awaiting description'), ('awaiting_confirmation', 'Awaiting confirmation'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('completed', 'Completed')], default='selecting_server', max_length=40)),
                ('problem_type', models.CharField(blank=True, max_length=40)),
                ('problem_description_redacted', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('last_message_at', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telegram_diagnostic_states', to='accounts.account')),
                ('chat_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_states', to='telegram_integration.telegramchatlink')),
                ('diagnostic_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_states', to='diagnostics.diagnosticsession')),
                ('selected_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telegram_diagnostic_states', to='applications.application')),
                ('selected_server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telegram_diagnostic_states', to='servers.server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telegram_diagnostic_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['chat_link', 'state', 'expires_at'], name='telegram_in_chat_li_5807a3_idx'), models.Index(fields=['account', 'state', 'created_at'], name='telegram_in_account_f5fa75_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state__in', ['selecting_server', 'selecting_application', 'selecting_problem_type', 'awaiting_description', 'awaiting_confirmation', 'active'])), fields=('chat_link',), name='unique_active_telegram_diagnostic_state_per_chat')],
            },
        ),
    ]
