# Generated by Django 5.2.14 on 2026-05-27 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('servers', '0002_agentregistrationtoken_baselinescan_scanneragent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BootstrapSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connecting', 'Connecting'), ('probing', 'Probing'), ('awaiting_package_confirmation', 'Awaiting package confirmation'), ('installing', 'Installing'), ('deploying', 'Deploying'), ('configuring', 'Configuring'), ('starting', 'Starting'), ('verifying_heartbeat', 'Verifying heartbeat'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=40)),
                ('target_host', models.CharField(blank=True, max_length=255)),
                ('ssh_port', models.PositiveIntegerField(default=22)),
                ('ssh_user', models.CharField(max_length=120)),
                ('auth_method', models.CharField(choices=[('password', 'Password'), ('private_key', 'Private key')], max_length=20)),
                ('confirm_package_install', models.BooleanField(default=False)),
                ('install_path', models.CharField(default='/opt/matrix_scanner', max_length=255)),
                ('service_name', models.CharField(default='matrix-scanner-agent.service', max_length=120)),
                ('agent_version', models.CharField(blank=True, max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bootstrap_sessions', to='accounts.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bootstrap_sessions', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bootstrap_sessions', to='servers.server')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BootstrapCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential_type', models.CharField(choices=[('ssh_password', 'SSH password'), ('ssh_private_key', 'SSH private key')], max_length=30)),
                ('encrypted_payload', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('destroyed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='bootstrap.bootstrapsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('install_method', models.CharField(default='remote_bootstrap', max_length=40)),
                ('install_path', models.CharField(default='/opt/matrix_scanner', max_length=255)),
                ('service_name', models.CharField(default='matrix-scanner-agent.service', max_length=120)),
                ('agent_version', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('installed', 'Installed'), ('failed', 'Failed'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_installations', to='accounts.account')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='servers.scanneragent')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_installations', to='servers.server')),
                ('bootstrap_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_installations', to='bootstrap.bootstrapsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BootstrapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_key', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('command_template_key', models.CharField(blank=True, max_length=120)),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('stdout_redacted', models.TextField(blank=True)),
                ('stderr_redacted', models.TextField(blank=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('structured_output', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='bootstrap.bootstrapsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='bootstrapsession',
            index=models.Index(fields=['account', 'status', 'created_at'], name='bootstrap_b_account_86e54d_idx'),
        ),
        migrations.AddIndex(
            model_name='bootstrapsession',
            index=models.Index(fields=['server', 'status', 'created_at'], name='bootstrap_b_server__1d9df5_idx'),
        ),
        migrations.AddIndex(
            model_name='agentinstallation',
            index=models.Index(fields=['account', 'status', 'created_at'], name='bootstrap_a_account_fa4066_idx'),
        ),
        migrations.AddIndex(
            model_name='agentinstallation',
            index=models.Index(fields=['server', 'status', 'created_at'], name='bootstrap_a_server__2980ff_idx'),
        ),
        migrations.AddIndex(
            model_name='bootstrapstep',
            index=models.Index(fields=['session', 'status', 'created_at'], name='bootstrap_b_session_df6e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='bootstrapstep',
            index=models.Index(fields=['step_key', 'status'], name='bootstrap_b_step_ke_e34582_idx'),
        ),
    ]
