# Generated by Django 5.2.14 on 2026-05-27 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('plans', '0001_initial'),
        ('servers', '0002_agentregistrationtoken_baselinescan_scanneragent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('runtime_handler_key', models.CharField(max_length=120)),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('default_timeout_seconds', models.PositiveIntegerField(default=30)),
                ('default_max_output_bytes', models.PositiveIntegerField(default=65536)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ToolDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('enabled', 'Enabled'), ('disabled', 'Disabled'), ('deprecated', 'Deprecated'), ('rejected', 'Rejected')], default='draft', max_length=30)),
                ('risk_level', models.CharField(choices=[('read_only', 'Read only'), ('sensitive_read', 'Sensitive read'), ('bootstrap_action', 'Bootstrap action'), ('write_action', 'Write action'), ('destructive_action', 'Destructive action')], default='read_only', max_length=30)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('default_params', models.JSONField(blank=True, default=dict)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('max_output_bytes', models.PositiveIntegerField(default=65536)),
                ('requires_path_policy', models.BooleanField(default=False)),
                ('allowed_path_prefixes', models.JSONField(blank=True, default=list)),
                ('blocked_path_prefixes', models.JSONField(blank=True, default=list)),
                ('redaction_rules', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tool_definitions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='definitions', to='tools.tooltemplate')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ToolPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_customer_run', models.BooleanField(default=True)),
                ('allow_admin_run', models.BooleanField(default=True)),
                ('allow_agent_run', models.BooleanField(default=True)),
                ('requires_approved_application', models.BooleanField(default=False)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('allowed_server_statuses', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('tool_definition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='tools.tooldefinition')),
            ],
            options={
                'ordering': ['tool_definition__key'],
            },
        ),
        migrations.CreateModel(
            name='PlanTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('monthly_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_tools', to='plans.plan')),
                ('tool_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_tools', to='tools.tooldefinition')),
            ],
            options={
                'ordering': ['plan__name', 'tool_definition__key'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'tool_definition'), name='unique_plan_tool_definition')],
            },
        ),
        migrations.CreateModel(
            name='ToolRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by_type', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('system', 'System')], default='system', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('timeout', 'Timeout'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('params_redacted', models.JSONField(blank=True, default=dict)),
                ('result_redacted', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('max_output_bytes', models.PositiveIntegerField(default=65536)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tool_runs', to='accounts.account')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tool_runs', to='servers.scanneragent')),
                ('agent_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_run', to='servers.agentjob')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_tool_runs', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tool_runs', to='servers.server')),
                ('tool_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tool_runs', to='tools.tooldefinition')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'status', 'created_at'], name='tools_toolr_account_1e0e3d_idx'), models.Index(fields=['server', 'status', 'created_at'], name='tools_toolr_server__eacfc8_idx'), models.Index(fields=['tool_definition', 'status', 'created_at'], name='tools_toolr_tool_de_0b268c_idx')],
            },
        ),
    ]
