# Generated by Django 5.2.14 on 2026-05-28 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_seed_baseline_tools'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolBuildRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('description_redacted', models.TextField(blank=True)),
                ('desired_tool_key', models.CharField(max_length=120)),
                ('desired_handler_key', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('proposed', 'Proposed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_build_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolBuildProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validation_failed', 'Validation failed'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted')], default='draft', max_length=30)),
                ('proposed_definition', models.JSONField(blank=True, default=dict)),
                ('proposed_policy', models.JSONField(blank=True, default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('converted_tool_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_proposals', to='tools.tooldefinition')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_build_proposals', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='tools.toolbuildrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolBuildReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_changes', 'Needs changes')], max_length=20)),
                ('notes_redacted', models.TextField(blank=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tools.toolbuildproposal')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_build_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed')], max_length=20)),
                ('test_type', models.CharField(default='mock_validation', max_length=80)),
                ('summary_redacted', models.TextField(blank=True)),
                ('result_redacted', models.JSONField(blank=True, default=dict)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='tools.toolbuildproposal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
