# Generated by Django 5.2.14 on 2026-06-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_seed_phase2_discovery_tool_contracts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooldefinition',
            name='allowed_binaries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tooldefinition',
            name='blocked_tokens',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tooldefinition',
            name='command_argv_template',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tooldefinition',
            name='execution_type',
            field=models.CharField(choices=[('runtime_handler', 'Runtime handler'), ('command_template', 'Command template'), ('script_template', 'Script template')], default='runtime_handler', max_length=30),
        ),
        migrations.AddField(
            model_name='tooltemplate',
            name='allowed_binaries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tooltemplate',
            name='blocked_tokens',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tooltemplate',
            name='command_argv_template',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tooltemplate',
            name='execution_type',
            field=models.CharField(choices=[('runtime_handler', 'Runtime handler'), ('command_template', 'Command template'), ('script_template', 'Script template')], default='runtime_handler', max_length=30),
        ),
    ]
