# Generated by Django 5.2.14 on 2026-06-05 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0002_adminchattoolrequest'),
        ('tools', '0006_tooldefinition_allowed_binaries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolbuildrequest',
            name='allowed_binaries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='toolbuildrequest',
            name='blocked_tokens',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='toolbuildrequest',
            name='command_argv_template',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='toolbuildrequest',
            name='desired_execution_type',
            field=models.CharField(choices=[('runtime_handler', 'Runtime handler'), ('command_template', 'Command template'), ('script_template', 'Script template')], default='runtime_handler', max_length=30),
        ),
        migrations.AddField(
            model_name='toolbuildrequest',
            name='expected_output_description_redacted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='toolbuildrequest',
            name='source_chat_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_build_requests', to='ai_chat.adminchatmessage'),
        ),
        migrations.AddField(
            model_name='toolbuildrequest',
            name='source_chat_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_build_requests', to='ai_chat.adminchatsession'),
        ),
    ]
