# Generated by Django 5.2.14 on 2026-05-28 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0002_application_metadata_and_more'),
        ('servers', '0003_baselinescan_current_step_baselinescan_error_message_and_more'),
        ('tools', '0003_seed_baseline_tools'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('waiting_for_approval', 'Waiting for approval'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('problem_type', models.CharField(choices=[('slowness', 'Slowness'), ('http_500', 'HTTP 500'), ('security_scan', 'Security scan'), ('laravel_production_audit', 'Laravel production audit'), ('custom', 'Custom')], default='custom', max_length=40)),
                ('user_prompt_redacted', models.TextField(blank=True)),
                ('summary_redacted', models.TextField(blank=True)),
                ('final_report_redacted', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('tool_run_count', models.PositiveIntegerField(default=0)),
                ('max_tool_runs', models.PositiveIntegerField(default=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_sessions', to='accounts.account')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_sessions', to='applications.application')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_diagnostic_sessions', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_sessions', to='servers.server')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('awaiting_approval', 'Awaiting approval'), ('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='planned', max_length=30)),
                ('step_type', models.CharField(choices=[('run_tool', 'Run tool'), ('ask_user', 'Ask user'), ('final_report', 'Final report'), ('stop', 'Stop')], default='run_tool', max_length=30)),
                ('tool_key', models.CharField(blank=True, max_length=120)),
                ('params_redacted', models.JSONField(blank=True, default=dict)),
                ('result_summary_redacted', models.TextField(blank=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_diagnostic_steps', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='diagnostics.diagnosticsession')),
                ('tool_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_step', to='tools.toolrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(choices=[('plan_step', 'Plan step'), ('approve_step', 'Approve step'), ('ingest_result', 'Ingest result'), ('final_report', 'Final report'), ('stop', 'Stop')], max_length=40)),
                ('input_context_redacted', models.JSONField(blank=True, default=dict)),
                ('output_json_redacted', models.JSONField(blank=True, default=dict)),
                ('reasoning_summary', models.TextField(blank=True)),
                ('created_by_type', models.CharField(choices=[('deterministic', 'Deterministic'), ('system', 'System')], default='deterministic', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='diagnostics.diagnosticsession')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='diagnostics.diagnosticstep')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='diagnosticsession',
            index=models.Index(fields=['account', 'status', 'created_at'], name='diagnostics_account_f024a1_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticsession',
            index=models.Index(fields=['server', 'status', 'created_at'], name='diagnostics_server__7ab562_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticstep',
            index=models.Index(fields=['session', 'status', 'created_at'], name='diagnostics_session_cccf01_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticdecision',
            index=models.Index(fields=['session', 'decision_type', 'created_at'], name='diagnostics_session_c41df4_idx'),
        ),
    ]
