# Generated by Django 5.2.14 on 2026-05-28 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
        ('telegram_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticsession',
            name='source',
            field=models.CharField(choices=[('portal', 'Portal'), ('telegram', 'Telegram')], default='portal', max_length=20),
        ),
        migrations.AddField(
            model_name='diagnosticsession',
            name='source_chat_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_sessions', to='telegram_integration.telegramchatlink'),
        ),
    ]
