# Generated by Django 5.2.14 on 2026-05-26 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('offline', 'Offline'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('agent_status', models.CharField(blank=True, max_length=50)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servers', to='accounts.account')),
            ],
            options={
                'ordering': ['account__name', 'name'],
            },
        ),
    ]
