# Generated by Django 5.2.14 on 2026-05-27 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0002_application_metadata_and_more'),
        ('servers', '0002_agentregistrationtoken_baselinescan_scanneragent_and_more'),
        ('tools', '0003_seed_baseline_tools'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='baselinescan',
            name='current_step',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='baselinescan',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='baselinescan',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_baseline_scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baselinescan',
            name='summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='BaselineScanStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_key', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('structured_output', models.JSONField(blank=True, default=dict)),
                ('baseline_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='servers.baselinescan')),
                ('tool_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_step', to='tools.toolrun')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('baseline_scan', 'step_key'), name='unique_baseline_scan_step')],
            },
        ),
        migrations.CreateModel(
            name='DiscoveredDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=255)),
                ('document_root', models.CharField(blank=True, max_length=1024)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discovered_domains', to='accounts.account')),
                ('baseline_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_domains', to='servers.baselinescan')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discovered_domains', to='servers.server')),
            ],
            options={
                'ordering': ['server__name', 'domain'],
                'constraints': [models.UniqueConstraint(fields=('account', 'server', 'domain'), name='unique_discovered_domain')],
            },
        ),
        migrations.CreateModel(
            name='DiscoveredService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(blank=True, max_length=80)),
                ('version', models.CharField(blank=True, max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discovered_services', to='accounts.account')),
                ('baseline_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_services', to='servers.baselinescan')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discovered_services', to='servers.server')),
            ],
            options={
                'ordering': ['server__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('account', 'server', 'name'), name='unique_discovered_service')],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='open', max_length=20)),
                ('severity', models.CharField(default='info', max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('evidence_summary', models.TextField(blank=True)),
                ('fingerprint', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='accounts.account')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='applications.application')),
                ('baseline_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='servers.baselinescan')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='servers.server')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('account', 'server', 'fingerprint'), name='unique_finding_fingerprint')],
            },
        ),
        migrations.CreateModel(
            name='LogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=1024)),
                ('source_type', models.CharField(blank=True, max_length=120)),
                ('exists', models.BooleanField(default=False)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_sources', to='accounts.account')),
                ('baseline_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_sources', to='servers.baselinescan')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_sources', to='servers.server')),
            ],
            options={
                'ordering': ['server__name', 'path'],
                'constraints': [models.UniqueConstraint(fields=('account', 'server', 'path'), name='unique_log_source')],
            },
        ),
    ]
