# Generated by Django 5.2.14 on 2026-05-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_baselinescan_current_step_baselinescan_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselinescan',
            name='profile_key',
            field=models.CharField(choices=[('legacy_cpanel', 'Legacy cPanel'), ('debian_nginx_opt', 'Debian / Nginx / opt'), ('minimal_linux', 'Minimal Linux')], default='legacy_cpanel', max_length=80),
        ),
    ]
