# Generated by Django 5.2.14 on 2026-06-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_baselinescan_profile_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentjob',
            name='execution_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
