# Generated by Django 5.2.14 on 2026-06-05 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0003_application_baseline_scan'),
        ('servers', '0004_baselinescan_profile_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('archived', 'Archived')], default='open', max_length=20)),
                ('title_redacted', models.CharField(blank=True, max_length=255)),
                ('context_snapshot_redacted', models.JSONField(blank=True, default=dict)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_chat_sessions', to='accounts.account')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_chat_sessions', to='applications.application')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_chat_sessions', to='servers.server')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('body_redacted', models.TextField(blank=True)),
                ('metadata_redacted', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_chat.adminchatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminChatDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision_type', models.CharField(choices=[('answer', 'Answer'), ('tool_suggestion', 'Tool suggestion'), ('tool_request', 'Tool request'), ('report_request', 'Report request'), ('tool_build_request', 'Tool build request')], max_length=40)),
                ('input_context_redacted', models.JSONField(blank=True, default=dict)),
                ('output_json_redacted', models.JSONField(blank=True, default=dict)),
                ('reasoning_summary', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='ai_chat.adminchatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='adminchatsession',
            index=models.Index(fields=['account', 'status', 'last_message_at'], name='ai_chat_adm_account_ddafd8_idx'),
        ),
        migrations.AddIndex(
            model_name='adminchatsession',
            index=models.Index(fields=['account', 'created_at'], name='ai_chat_adm_account_771240_idx'),
        ),
        migrations.AddIndex(
            model_name='adminchatmessage',
            index=models.Index(fields=['session', 'created_at'], name='ai_chat_adm_session_635ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='adminchatdecision',
            index=models.Index(fields=['session', 'decision_type', 'created_at'], name='ai_chat_adm_session_50c3b1_idx'),
        ),
    ]
