# Generated by Django 5.2.14 on 2026-06-05 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0001_initial'),
        ('tools', '0005_seed_phase2_discovery_tool_contracts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminChatToolRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('params_redacted', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('approved', 'Approved'), ('queued', 'Queued'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='suggested', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('error_summary', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_chat_tool_requests', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_requests', to='ai_chat.adminchatmessage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_requests', to='ai_chat.adminchatsession')),
                ('tool_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_tool_requests', to='tools.tooldefinition')),
                ('tool_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_tool_requests', to='tools.toolrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'status', 'created_at'], name='ai_chat_adm_session_39c453_idx'), models.Index(fields=['tool_definition', 'status'], name='ai_chat_adm_tool_de_b8a6d7_idx')],
            },
        ),
    ]
