# Generated by Django 5.2.14 on 2026-06-05 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0002_adminchattoolrequest'),
        ('reports', '0002_alter_report_report_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminChatReportDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('technical_internal', 'Technical/internal'), ('customer_summary', 'Customer summary')], max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted')], default='draft', max_length=20)),
                ('title_redacted', models.CharField(blank=True, max_length=255)),
                ('summary_redacted', models.TextField(blank=True)),
                ('sections_redacted', models.JSONField(blank=True, default=list)),
                ('source_snapshot_redacted', models.JSONField(blank=True, default=dict)),
                ('review_notes_redacted', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('converted_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_report_drafts', to='reports.report')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chat_report_drafts', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_drafts', to='ai_chat.adminchatmessage')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_chat_report_drafts', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_drafts', to='ai_chat.adminchatsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'status', 'created_at'], name='ai_chat_adm_session_ad7564_idx'), models.Index(fields=['report_type', 'status', 'created_at'], name='ai_chat_adm_report__213cda_idx')],
            },
        ),
    ]
