# Generated by Django 5.2.14 on 2026-06-06 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ai_chat', '0003_adminchatreportdraft'),
        ('applications', '0003_application_baseline_scan'),
        ('servers', '0005_agentjob_execution_payload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='adminchatsession',
            name='ai_chat_adm_account_ddafd8_idx',
        ),
        migrations.AddField(
            model_name='adminchatsession',
            name='channel',
            field=models.CharField(choices=[('portal_customer', 'Portal customer'), ('admin_internal', 'Admin internal')], default='portal_customer', max_length=30),
        ),
        migrations.AddIndex(
            model_name='adminchatsession',
            index=models.Index(fields=['account', 'channel', 'status', 'last_message_at'], name='ai_chat_adm_account_f827a3_idx'),
        ),
    ]
