# Generated by Django 5.2.14 on 2026-06-23 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ai_chat', '0004_remove_adminchatsession_ai_chat_adm_account_ddafd8_idx_and_more'),
        ('applications', '0003_application_baseline_scan'),
        ('servers', '0005_agentjob_execution_payload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLiveAIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_identifier', models.CharField(blank=True, max_length=320)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('safe_context_size_bytes', models.PositiveIntegerField(default=0)),
                ('response_size_bytes', models.PositiveIntegerField(default=0)),
                ('error_class', models.CharField(blank=True, choices=[('disabled', 'Disabled'), ('missing_config', 'Missing config'), ('auth_error', 'Auth error'), ('rate_limited', 'Rate limited'), ('timeout', 'Timeout'), ('upstream_error', 'Upstream error'), ('validation_error', 'Validation error'), ('unknown_error', 'Unknown error')], max_length=40)),
                ('fallback_used', models.BooleanField(default=False)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_live_ai_request_logs', to='accounts.account')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_live_ai_request_logs', to='applications.application')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_live_ai_request_logs', to='servers.server')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_ai_request_logs', to='ai_chat.adminchatsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_live_ai_request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='ai_chat_adm_status_6322bf_idx'), models.Index(fields=['model', 'created_at'], name='ai_chat_adm_model_c636c6_idx'), models.Index(fields=['user', 'created_at'], name='ai_chat_adm_user_id_d23887_idx'), models.Index(fields=['account', 'created_at'], name='ai_chat_adm_account_85e1cc_idx'), models.Index(fields=['session', 'created_at'], name='ai_chat_adm_session_913ce6_idx'), models.Index(fields=['error_class', 'created_at'], name='ai_chat_adm_error_c_93f9cc_idx')],
            },
        ),
    ]
