# Generated by Django 5.2.14 on 2026-05-26 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('path', models.CharField(blank=True, max_length=1024)),
                ('framework', models.CharField(blank=True, max_length=100)),
                ('review_status', models.CharField(choices=[('pending_review', 'Pending review'), ('approved', 'Approved'), ('ignored', 'Ignored'), ('archived', 'Archived')], default='pending_review', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='accounts.account')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='servers.server')),
            ],
            options={
                'ordering': ['account__name', 'name'],
            },
        ),
    ]
