# Generated by Django 5.2.14 on 2026-05-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0001_initial'),
        ('servers', '0002_agentregistrationtoken_baselinescan_scanneragent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('account', 'server', 'domain', 'path'), name='unique_application_location'),
        ),
    ]
