# Generated by Django 5.2.14 on 2026-06-04 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_metadata_and_more'),
        ('servers', '0004_baselinescan_profile_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='baseline_scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='servers.baselinescan'),
        ),
    ]
