# Generated by Django 5.2.14 on 2026-05-28 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0002_application_metadata_and_more'),
        ('diagnostics', '0002_diagnosticsession_source_and_more'),
        ('servers', '0003_baselinescan_current_step_baselinescan_error_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('account', 'Account'), ('server', 'Server'), ('application', 'Application')], default='global', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body_redacted', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('internal', 'Internal'), ('customer_visible', 'Customer visible')], default='internal', max_length=30)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_entries', to='accounts.account')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_entries', to='applications.application')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_knowledge_entries', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_entries', to='servers.server')),
            ],
            options={
                'ordering': ['scope', 'title'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(max_length=80)),
                ('source_id', models.CharField(blank=True, max_length=120)),
                ('title_redacted', models.CharField(blank=True, max_length=255)),
                ('summary_redacted', models.TextField(blank=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='reports.knowledgeentry')),
            ],
            options={
                'ordering': ['entry', 'source_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('baseline_report', 'Baseline report'), ('diagnostic_report', 'Diagnostic report'), ('server_health_summary', 'Server health summary'), ('findings_summary', 'Findings summary')], max_length=40)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('archived', 'Archived')], default='generated', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('summary_redacted', models.TextField(blank=True)),
                ('source_snapshot_redacted', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='accounts.account')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='applications.application')),
                ('baseline_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='servers.baselinescan')),
                ('diagnostic_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='diagnostics.diagnosticsession')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='servers.server')),
            ],
            options={
                'ordering': ['-generated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('body_redacted', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='info', max_length=20)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='accounts.account')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='applications.application')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recommendations', to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='servers.finding')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='servers.server')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='reports.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_type', models.CharField(choices=[('summary', 'Summary'), ('evidence', 'Evidence'), ('timeline', 'Timeline'), ('tools_executed', 'Tools executed'), ('findings', 'Findings'), ('recommendations', 'Recommendations'), ('developer_notes', 'Developer notes')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('body_redacted', models.TextField(blank=True)),
                ('data_redacted', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.report')),
            ],
            options={
                'ordering': ['report', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FindingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fingerprint', models.CharField(max_length=255)),
                ('normalized_fingerprint', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='info', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='open', max_length=20)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('occurrence_count', models.PositiveIntegerField(default=0)),
                ('summary_redacted', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finding_groups', to='accounts.account')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finding_groups', to='applications.application')),
                ('latest_finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_latest_for', to='servers.finding')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finding_groups', to='servers.server')),
            ],
            options={
                'ordering': ['-last_seen_at', '-created_at'],
                'indexes': [models.Index(fields=['account', 'server', 'normalized_fingerprint'], name='reports_fin_account_7ae6e8_idx'), models.Index(fields=['account', 'severity', 'status'], name='reports_fin_account_648cc5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgeentry',
            index=models.Index(fields=['scope', 'status', 'visibility'], name='reports_kno_scope_b92d51_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeentry',
            index=models.Index(fields=['account', 'status', 'visibility'], name='reports_kno_account_4b4e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['account', 'report_type', 'created_at'], name='reports_rep_account_b40757_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['server', 'report_type', 'created_at'], name='reports_rep_server__ab0a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['account', 'status', 'priority'], name='reports_rec_account_cb9e48_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['report', 'status'], name='reports_rec_report__4bf531_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsection',
            index=models.Index(fields=['report', 'section_type'], name='reports_rep_report__4f5c9b_idx'),
        ),
    ]
