# Generated by Django 5.2.14 on 2026-06-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('baseline_report', 'Baseline report'), ('diagnostic_report', 'Diagnostic report'), ('server_health_summary', 'Server health summary'), ('findings_summary', 'Findings summary'), ('technical_internal', 'Technical/internal'), ('customer_summary', 'Customer summary')], max_length=40),
        ),
    ]
